/*
 * Copyright (c) 2013,2014 Jens Deters http://www.jensd.de
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 */

package org.husonlab.phylosketch.utils;

import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.text.Font;

import java.io.IOException;
import java.util.Objects;

/**
 * Icon Enum based on Font-Awesome v4.1.0
 * <p>
 * Font Awesome uses the Unicode Private Use Area (PUA) to ensure screen readers
 * do not read off random characters that represent icons
 *
 * @author Jens Deters
 */
public enum AwesomeIcon {
	ADJUST('\uf042'),
	ADN('\uf170'),
	ALIGN_CENTER('\uf037'),
	ALIGN_JUSTIFY('\uf039'),
	ALIGN_LEFT('\uf036'),
	ALIGN_RIGHT('\uf038'),
	AMBULANCE('\uf0f9'),
	ANCHOR('\uf13d'),
	ANDROID('\uf17b'),
	ANGLE_DOUBLE_DOWN('\uf103'),
	ANGLE_DOUBLE_LEFT('\uf100'),
	ANGLE_DOUBLE_RIGHT('\uf101'),
	ANGLE_DOUBLE_UP('\uf102'),
	ANGLE_DOWN('\uf107'),
	ANGLE_LEFT('\uf104'),
	ANGLE_RIGHT('\uf105'),
	ANGLE_UP('\uf106'),
	APPLE('\uf179'),
	ARCHIVE('\uf187'),
	ARROWS('\uf047'),
	ARROWS_ALT('\uf0b2'),
	ARROWS_H('\uf07e'),
	ARROWS_V('\uf07d'),
	ARROW_CIRCLE_ALT_DOWN('\uf01a'),
	ARROW_CIRCLE_ALT_LEFT('\uf190'),
	ARROW_CIRCLE_ALT_RIGHT('\uf18e'),
	ARROW_CIRCLE_ALT_UP('\uf01b'),
	ARROW_CIRCLE_DOWN('\uf0ab'),
	ARROW_CIRCLE_LEFT('\uf0a8'),
	ARROW_CIRCLE_RIGHT('\uf0a9'),
	ARROW_CIRCLE_UP('\uf0aa'),
	ARROW_DOWN('\uf063'),
	ARROW_LEFT('\uf060'),
	ARROW_RIGHT('\uf061'),
	ARROW_UP('\uf062'),
	ASTERISK('\uf069'),
	AUTOMOBILE('\uf1b9'),
	BACKWARD('\uf04a'),
	BAN('\uf05e'),
	BANK('\uf19c'),
	BARCODE('\uf02a'),
	BARS('\uf0c9'),
	BAR_CHART_ALT('\uf080'),
	BEER('\uf0fc'),
	BEHANCE('\uf1b4'),
	BEHANCE_SQUARE('\uf1b5'),
	BELL('\uf0f3'),
	BELL_ALT('\uf0a2'),
	BITBUCKET('\uf171'),
	BITBUCKET_SQUARE('\uf172'),
	BITCOIN('\uf15a'),
	BOLD('\uf032'),
	BOLT('\uf0e7'),
	BOMB('\uf1e2'),
	BOOK('\uf02d'),
	BOOKMARK('\uf02e'),
	BOOKMARK_ALT('\uf097'),
	BRIEFCASE('\uf0b1'),
	BTC('\uf15a'),
	BUG('\uf188'),
	BUILDING('\uf1ad'),
	BUILDING_ALT('\uf0f7'),
	BULLHORN('\uf0a1'),
	BULLSEYE('\uf140'),
	CAB('\uf1ba'),
	CALENDAR('\uf073'),
	CALENDAR_ALT('\uf133'),
	CAMERA('\uf030'),
	CAMERA_RETRO('\uf083'),
	CAR('\uf1b9'),
	CARET_DOWN('\uf0d7'),
	CARET_LEFT('\uf0d9'),
	CARET_RIGHT('\uf0da'),
	CARET_SQUARE_ALT_DOWN('\uf150'),
	CARET_SQUARE_ALT_LEFT('\uf191'),
	CARET_SQUARE_ALT_RIGHT('\uf152'),
	CARET_SQUARE_ALT_UP('\uf151'),
	CARET_UP('\uf0d8'),
	CERTIFICATE('\uf0a3'),
	CHAIN('\uf0c1'),
	CHAIN_BROKEN('\uf127'),
	CHECK('\uf00c'),
	CHECK_CIRCLE('\uf058'),
	CHECK_CIRCLE_ALT('\uf05d'),
	CHECK_SQUARE('\uf14a'),
	CHECK_SQUARE_ALT('\uf046'),
	CHEVRON_CIRCLE_DOWN('\uf13a'),
	CHEVRON_CIRCLE_LEFT('\uf137'),
	CHEVRON_CIRCLE_RIGHT('\uf138'),
	CHEVRON_CIRCLE_UP('\uf139'),
	CHEVRON_DOWN('\uf078'),
	CHEVRON_LEFT('\uf053'),
	CHEVRON_RIGHT('\uf054'),
	CHEVRON_UP('\uf077'),
	CHILD('\uf1ae'),
	CIRCLE('\uf111'),
	CIRCLE_ALT('\uf10c'),
	CIRCLE_ALT_NOTCH('\uf1ce'),
	CIRCLE_THIN('\uf1db'),
	CLIPBOARD('\uf0ea'),
	CLOCK_ALT('\uf017'),
	CLOUD('\uf0c2'),
	CLOUD_DOWNLOAD('\uf0ed'),
	CLOUD_UPLOAD('\uf0ee'),
	CNY('\uf157'),
	CODE('\uf121'),
	CODEPEN('\uf1cb'),
	CODE_FORK('\uf126'),
	COFFEE('\uf0f4'),
	COG('\uf013'),
	COGS('\uf085'),
	COLUMNS('\uf0db'),
	COMMENT('\uf075'),
	COMMENTS('\uf086'),
	COMMENTS_ALT('\uf0e6'),
	COMMENT_ALT('\uf0e5'),
	COMPASS('\uf14e'),
	COMPRESS('\uf066'),
	COPY('\uf0c5'),
	CREDIT_CARD('\uf09d'),
	CROP('\uf125'),
	CROSSHAIRS('\uf05b'),
	CSS3('\uf13c'),
	CUBE('\uf1b2'),
	CUBES('\uf1b3'),
	CUT('\uf0c4'),
	CUTLERY('\uf0f5'),
	DASHBOARD('\uf0e4'),
	DATABASE('\uf1c0'),
	DEDENT('\uf03b'),
	DELICIOUS('\uf1a5'),
	DESKTOP('\uf108'),
	DEVIANTART('\uf1bd'),
	DIGG('\uf1a6'),
	DOLLAR('\uf155'),
	DOT_CIRCLE_ALT('\uf192'),
	DOWNLOAD('\uf019'),
	DRIBBBLE('\uf17d'),
	DROPBOX('\uf16b'),
	DRUPAL('\uf1a9'),
	EDIT('\uf03e'),
	EJECT('\uf052'),
	ELLIPSIS_H('\uf141'),
	ELLIPSIS_V('\uf142'),
	EMPIRE('\uf1d1'),
	ENVELOPE('\uf0e0'),
	ENVELOPE_ALT('\uf003'),
	ENVELOPE_SQUARE('\uf199'),
	ERASER('\uf12d'),
	EUR('\uf153'),
	EURO('\uf153'),
	EXCHANGE('\uf0ec'),
	EXCLAMATION('\uf12a'),
	EXCLAMATION_CIRCLE('\uf06a'),
	EXCLAMATION_TRIANGLE('\uf071'),
	EXPAND('\uf065'),
	EXTERNAL_LINK('\uf08e'),
	EXTERNAL_LINK_SQUARE('\uf14c'),
	EYE('\uf06e'),
	EYE_SLASH('\uf070'),
	FACEBOOK('\uf09a'),
	FACEBOOK_SQUARE('\uf082'),
	FAST_BACKWARD('\uf049'),
	FAST_FORWARD('\uf050'),
	FAX('\uf1ac'),
	FEMALE('\uf182'),
	FIGHTER_JET('\uf0fb'),
	FILE('\uf15b'),
	FILES_ALT('\uf0c5'),
	FILE_ALT('\uf016'),
	FILE_ARCHIVE_ALT('\uf1c6'),
	FILE_AUDIO_ALT('\uf1c7'),
	FILE_CODE_ALT('\uf1c9'),
	FILE_EXCEL_ALT('\uf1c3'),
	FILE_IMAGE_ALT('\uf1c5'),
	FILE_MOVIE_ALT('\uf1c8'),
	FILE_PDF_ALT('\uf1c1'),
	FILE_PHOTO_ALT('\uf1c5'),
	FILE_PICTURE_ALT('\uf1c5'),
	FILE_POWERPOINT_ALT('\uf1c4'),
	FILE_SOUND_ALT('\uf1c7'),
	FILE_TEXT('\uf15c'),
	FILE_TEXT_ALT('\uf0f6'),
	FILE_VIDEO_ALT('\uf1c8'),
	FILE_WORD_ALT('\uf1c2'),
	FILE_ZIP_ALT('\uf1c6'),
	FILM('\uf008'),
	FILTER('\uf0b0'),
	FIRE('\uf06d'),
	FIRE_EXTINGUISHER('\uf134'),
	FLAG('\uf024'),
	FLAG_ALT('\uf11d'),
	FLAG_CHECKERED('\uf11e'),
	FLASH('\uf0e7'),
	FLASK('\uf0c3'),
	FLICKR('\uf16e'),
	FLOPPY_ALT('\uf0c7'),
	FOLDER('\uf07b'),
	FOLDER_ALT('\uf114'),
	FOLDER_OPEN('\uf07c'),
	FOLDER_OPEN_ALT('\uf115'),
	FONT('\uf031'),
	FORWARD('\uf04e'),
	FOURSQUARE('\uf180'),
	FROWN_ALT('\uf119'),
	GAMEPAD('\uf11b'),
	GAVEL('\uf0e3'),
	GBP('\uf154'),
	GE('\uf1d1'),
	GEAR('\uf013'),
	GEARS('\uf085'),
	GIFT('\uf06b'),
	GIT('\uf1d3'),
	GITHUB('\uf09b'),
	GITHUB_ALT('\uf113'),
	GITHUB_SQUARE('\uf092'),
	GITTIP('\uf184'),
	GIT_SQUARE('\uf1d2'),
	GLASS('\uf000'),
	GLOBE('\uf0ac'),
	GOOGLE('\uf1a0'),
	GOOGLE_PLUS('\uf0d5'),
	GOOGLE_PLUS_SQUARE('\uf0d4'),
	GRADUATION_CAP('\uf19d'),
	GROUP('\uf0c0'),
	HACKER_NEWS('\uf1d4'),
	HAND_ALT_DOWN('\uf0a7'),
	HAND_ALT_LEFT('\uf0a5'),
	HAND_ALT_RIGHT('\uf0a4'),
	HAND_ALT_UP('\uf0a6'),
	HDD_ALT('\uf0a0'),
	HEADER('\uf1dc'),
	HEADPHONES('\uf025'),
	HEART('\uf004'),
	HEART_ALT('\uf08a'),
	HISTORY('\uf1da'),
	HOME('\uf015'),
	HOSPITAL_ALT('\uf0f8'),
	HTML5('\uf13b'),
	H_SQUARE('\uf0fd'),
	IMAGE('\uf03e'),
	INBOX('\uf01c'),
	INDENT('\uf03c'),
	INFO('\uf129'),
	INFO_CIRCLE('\uf05a'),
	INR('\uf156'),
	INSTAGRAM('\uf16d'),
	INSTITUTION('\uf19c'),
	ITALIC('\uf033'),
	JOOMLA('\uf1aa'),
	JPY('\uf157'),
	JSFIDDLE('\uf1cc'),
	KEY('\uf084'),
	KEYBOARD_ALT('\uf11c'),
	KRW('\uf159'),
	LANGUAGE('\uf1ab'),
	LAPTOP('\uf109'),
	LEAF('\uf06c'),
	LEGAL('\uf0e3'),
	LEMON_ALT('\uf094'),
	LEVEL_DOWN('\uf149'),
	LEVEL_UP('\uf148'),
	LIFE_BOUY('\uf1cd'),
	LIFE_RING('\uf1cd'),
	LIFE_SAVER('\uf1cd'),
	LIGHTBULB_ALT('\uf0eb'),
	LINK('\uf0c1'),
	LINKEDIN('\uf0e1'),
	LINKEDIN_SQUARE('\uf08c'),
	LINUX('\uf17c'),
	LIST('\uf03a'),
	LIST_ALT('\uf022'),
	LIST_OL('\uf0cb'),
	LIST_UL('\uf0ca'),
	LOCATION_ARROW('\uf124'),
	LOCK('\uf023'),
	LONG_ARROW_DOWN('\uf175'),
	LONG_ARROW_LEFT('\uf177'),
	LONG_ARROW_RIGHT('\uf178'),
	LONG_ARROW_UP('\uf176'),
	MAGIC('\uf0d0'),
	MAGNET('\uf076'),
	MAIL_FORWARD('\uf064'),
	MAIL_REPLY('\uf112'),
	MAIL_REPLY_ALL('\uf122'),
	MALE('\uf183'),
	MAP_MARKER('\uf041'),
	MAXCDN('\uf136'),
	MEDKIT('\uf0fa'),
	MEH_ALT('\uf11a'),
	MICROPHONE('\uf130'),
	MICROPHONE_SLASH('\uf131'),
	MINUS('\uf068'),
	MINUS_CIRCLE('\uf056'),
	MINUS_SQUARE('\uf146'),
	MINUS_SQUARE_ALT('\uf147'),
	MOBILE('\uf10b'),
	MOBILE_PHONE('\uf10b'),
	MONEY('\uf0d6'),
	MOON_ALT('\uf186'),
	MORTAR_BOARD('\uf19d'),
	MUSIC('\uf001'),
	NAVICON('\uf0c9'),
	OPENID('\uf19b'),
	OUTDENT('\uf03b'),
	PAGELINES('\uf18c'),
	PAPERCLIP('\uf0c6'),
	PAPER_PLANE('\uf1d8'),
	PAPER_PLANE_ALT('\uf1d9'),
	PARAGRAPH('\uf1dd'),
	PASTE('\uf0ea'),
	PAUSE('\uf04c'),
	PAW('\uf1b0'),
	PENCIL('\uf040'),
	PENCIL_SQUARE('\uf14b'),
	PENCIL_SQUARE_ALT('\uf03e'),
	PHONE('\uf095'),
	PHONE_SQUARE('\uf098'),
	PHOTO('\uf03e'),
	PICTURE_ALT('\uf03e'),
	PIED_PIPER('\uf1a7'),
	PIED_PIPER_ALT('\uf1a8'),
	PIED_PIPER_SQUARE('\uf1a7'),
	PINTEREST('\uf0d2'),
	PINTEREST_SQUARE('\uf0d3'),
	PLANE('\uf072'),
	PLAY('\uf04b'),
	PLAY_CIRCLE('\uf144'),
	PLAY_CIRCLE_ALT('\uf01d'),
	PLUS('\uf067'),
	PLUS_CIRCLE('\uf055'),
	PLUS_SQUARE('\uf0fe'),
	PLUS_SQUARE_ALT('\uf196'),
	POWER_OFF('\uf011'),
	PRINT('\uf02F'),
	PUZZLE_PIECE('\uf12e'),
	QQ('\uf1d6'),
	QRCODE('\uf029'),
	QUESTION('\uf128'),
	QUESTION_CIRCLE('\uf059'),
	QUOTE_LEFT('\uf10d'),
	QUOTE_RIGHT('\uf10e'),
	RA('\uf1d0'),
	RANDOM('\uf074'),
	REBEL('\uf1d0'),
	RECYCLE('\uf1b8'),
	REDDIT('\uf1a1'),
	REDDIT_SQUARE('\uf1a2'),
	REFRESH('\uf021'),
	RENREN('\uf18b'),
	REORDER('\uf0c9'),
	REPEAT('\uf01e'),
	REPLY('\uf112'),
	REPLY_ALL('\uf122'),
	RETWEET('\uf079'),
	RMB('\uf157'),
	ROAD('\uf018'),
	ROCKET('\uf135'),
	ROTATE_LEFT('\uf0e2'),
	ROTATE_RIGHT('\uf01e'),
	ROUBLE('\uf158'),
	RSS('\uf09e'),
	RSS_SQUARE('\uf143'),
	RUB('\uf158'),
	RUBLE('\uf158'),
	RUPEE('\uf156'),
	SAVE('\uf0c7'),
	SCISSORS('\uf0c4'),
	SEARCH('\uf002'),
	SEARCH_MINUS('\uf010'),
	SEARCH_PLUS('\uf00e'),
	SEND('\uf1d8'),
	SEND_ALT('\uf1d9'),
	SHARE('\uf064'),
	SHARE_ALT('\uf1e0'),
	SHARE_ALT_SQUARE('\uf1e1'),
	SHARE_SQUARE('\uf14d'),
	SHARE_SQUARE_ALT('\uf045'),
	SHIELD('\uf132'),
	SHOPPING_CART('\uf07a'),
	SIGNAL('\uf012'),
	SIGN_IN('\uf090'),
	SIGN_OUT('\uf08b'),
	SITEMAP('\uf0e8'),
	SKYPE('\uf17e'),
	SLACK('\uf198'),
	SLIDERS('\uf1de'),
	SMILE_ALT('\uf118'),
	SORT('\uf0dc'),
	SORT_ALPHA_ASC('\uf15d'),
	SORT_ALPHA_DESC('\uf15e'),
	SORT_AMOUNT_ASC('\uf160'),
	SORT_AMOUNT_DESC('\uf161'),
	SORT_ASC('\uf0de'),
	SORT_DESC('\uf0dd'),
	SORT_DOWN('\uf0dd'),
	SORT_NUMERIC_ASC('\uf162'),
	SORT_NUMERIC_DESC('\uf163'),
	SORT_UP('\uf0de'),
	SOUNDCLOUD('\uf1be'),
	SPACE_SHUTTLE('\uf197'),
	SPINNER('\uf110'),
	SPOON('\uf1b1'),
	SPOTIFY('\uf1bc'),
	SQUARE('\uf0c8'),
	SQUARE_ALT('\uf096'),
	STACK_EXCHANGE('\uf18d'),
	STACK_OVERFLOW('\uf16c'),
	STAR('\uf005'),
	STAR_ALT('\uf006'),
	STAR_HALF('\uf089'),
	STAR_HALF_ALT('\uf123'),
	STAR_HALF_EMPTY('\uf123'),
	STAR_HALF_FULL('\uf123'),
	STEAM('\uf1b6'),
	STEAM_SQUARE('\uf1b7'),
	STEP_BACKWARD('\uf048'),
	STEP_FORWARD('\uf051'),
	STETHOSCOPE('\uf0f1'),
	STOP('\uf04d'),
	STRIKETHROUGH('\uf0cc'),
	STUMBLEUPON('\uf1a4'),
	STUMBLEUPON_CIRCLE('\uf1a3'),
	SUBSCRIPT('\uf12c'),
	SUITCASE('\uf0f2'),
	SUN_ALT('\uf185'),
	SUPERSCRIPT('\uf12b'),
	SUPPORT('\uf1cd'),
	TABLE('\uf0ce'),
	TABLET('\uf10a'),
	TACHOMETER('\uf0e4'),
	TAG('\uf02b'),
	TAGS('\uf02c'),
	TASKS('\uf0ae'),
	TAXI('\uf1ba'),
	TENCENT_WEIBO('\uf1d5'),
	TERMINAL('\uf120'),
	TEXT_HEIGHT('\uf034'),
	TEXT_WIDTH('\uf035'),
	TH('\uf00a'),
	THUMBS_ALT_DOWN('\uf088'),
	THUMBS_ALT_UP('\uf087'),
	THUMBS_DOWN('\uf165'),
	THUMBS_UP('\uf164'),
	THUMB_TACK('\uf08d'),
	TH_LARGE('\uf009'),
	TH_LIST('\uf00b'),
	TICKET('\uf145'),
	TIMES('\uf00d'),
	TIMES_CIRCLE('\uf057'),
	TIMES_CIRCLE_ALT('\uf05c'),
	TINT('\uf043'),
	TOGGLE_DOWN('\uf150'),
	TOGGLE_LEFT('\uf191'),
	TOGGLE_RIGHT('\uf152'),
	TOGGLE_UP('\uf151'),
	TRASH_ALT('\uf014'),
	TREE('\uf1bb'),
	TRELLO('\uf181'),
	TROPHY('\uf091'),
	TRUCK('\uf0d1'),
	TRY('\uf195'),
	TUMBLR('\uf173'),
	TUMBLR_SQUARE('\uf174'),
	TURKISH_LIRA('\uf195'),
	TWITTER('\uf099'),
	TWITTER_SQUARE('\uf081'),
	UMBRELLA('\uf0e9'),
	UNDERLINE('\uf0cd'),
	UNDO('\uf0e2'),
	UNIVERSITY('\uf19c'),
	UNLINK('\uf127'),
	UNLOCK('\uf09c'),
	UNLOCK_ALT('\uf13e'),
	UNSORTED('\uf0dc'),
	UPLOAD('\uf093'),
	USD('\uf155'),
	USER('\uf007'),
	USERS('\uf0c0'),
	USER_MD('\uf0f0'),
	VIDEO_CAMERA('\uf03d'),
	VIMEO_SQUARE('\uf194'),
	VINE('\uf1ca'),
	VK('\uf189'),
	VOLUME_DOWN('\uf027'),
	VOLUME_OFF('\uf026'),
	VOLUME_UP('\uf028'),
	WARNING('\uf071'),
	WECHAT('\uf1d7'),
	WEIBO('\uf18a'),
	WEIXIN('\uf1d7'),
	WHEELCHAIR('\uf193'),
	WINDOWS('\uf17a'),
	WON('\uf159'),
	WORDPRESS('\uf19a'),
	WRENCH('\uf0ad'),
	XING('\uf168'),
	XING_SQUARE('\uf169'),
	YAHOO('\uf19e'),
	YEN('\uf157'),
	YOUTUBE('\uf167'),
	YOUTUBE_PLAY('\uf16a'),
	YOUTUBE_SQUARE('\uf166');

	// static public ArrayList<Pair<String,Node>> all=new ArrayList<>();

	static {
		try (var ins = Objects.requireNonNull(AwesomeIcon.class.getResource("fontawesome-webfont.ttf")).openStream()) {
			Font.loadFont(ins, 10);
			/*
			for(int i=0;i<13278;i++) {
				all.add(new Pair<>(String.valueOf(i),graphic(String.valueOf((char)i),null)));
			}
			*/
		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}

	private final Character character;

	AwesomeIcon(Character character) {
		this.character = character;
	}

	public Character getChar() {
		return character;
	}

	public String toUnicode() {
		return String.format("\\u%04x", (int) character);
	}

	@Override
	public String toString() {
		return character.toString();
	}

	public Node graphic(String style) {
		return graphic(toString(), style);
	}

	public static Node graphic(String ch, String style) {
		var label = new Label(ch);
		label.getStyleClass().add("icon-text");
		label.setAlignment(Pos.CENTER);
		label.setStyle("-fx-font-family: FontAwesome; -fx-font-size: 16; -fx-padding:0 3 0 3; -fx-background-color: transparent;" + (style != null ? style : ""));
		return label;
	}

	public Node graphic() {
		return this.graphic(null);
	}

	public Button button() {
		return this.button(null);
	}

	public Button button(EventHandler<ActionEvent> handler) {
		var button = new Button(this.toString());
		button.getStyleClass().add("icon-toggle");
		button.setStyle("-fx-font-family: FontAwesome; -fx-font-size: 16;");
		if (handler != null) {
			button.setOnAction(handler);
		}

		return button;
	}
}